ksnyder1986/Warhammer-40k-3rd-Edition

Cursed Foundings (Chapter Approved 2004).cat
Space Marines (1999).cat

Cursed foundings

---

Biel-Tan Swordwind Army (2000).cat
Eldar (2000).cat
Iyanden Ghost Warriors (2000).cat
Rangers of Alaitoc (2000).cat
Saim-Hann Wild Rider Host (2000).cat
Ulthwe Strike Force (Eye of Terror 2003).cat
Ulthwe The Damned (2000).cat

Craftworlds

---

Tyranid Seeding Swarm (Chapter Approved 2003).cat
Tyranids (2001).cat

Seeding swarms

---

Chaos Space Marines (2002).cat

fix aspiring champion discount costs

---

Black Templars (2000).cat
Blood Angels (1998).cat
Chaos Space Marines (2002).cat
Dark Angels (1999).cat
Imperial Guard (2003).cat
Necrons (2002).cat
Salamanders (2000).cat
Space Marines (1999).cat
Space Wolves (2000).cat
Tau (2001).cat
Warhammer 40k 3rd Edition.gst

adding in vehicles that are not in 3rd edition codexes or in IA for 3rd edition. used the VDR to do most of it. I needed to invent some points for certain weapons that did not exist in 3rd edition (such as Tesla weapons).

Homebrew vehicles

---

Black Templars (2000).cat
Blood Angels (1998).cat
Dark Angels (1999).cat
Imperial Fists (2003).cat
Space Marines (1999).cat
White Scars (2002).cat

From the Index Astartes books published in 2002 and 2003.
Closes #57 #58

Add White Scars and Imperial Fists

---

Squats (Unofficial 2000).cat

fix vehicle options

---

Orks (1999).cat

Fix Flashgitz Bug

---

Daemon Hunters (2003).cat
Sisters of Battle (Chapter Approved 2001).cat

Create Sisters of Battle (Chapter Approved 2001).cat

---

Elysian Drop Troops (2003).cat
Warhammer 40k 3rd Edition.gst

Pushing changes to the Elysian Drop Troop list
* fixed the cost on stormtroopers
* made weapon options easier to understand
* general tidyup

Elysian Drop Troops update

---

Elysian Drop Troops (2003).cat

Didn't increase the revision number some the BS app wasn't download the updated version.
Fixed the BS value for the Veteran Sergeant in the Stormtrooper Squads.

Small update to Elysian list

---

Armoured Company (2001).cat
Catachan (2000).cat
Cityfighting Imperial Guard (2003).cat
Death Korps of Krieg (2003).cat
Eldar (2000).cat
Elysian Drop Troops (2003).cat
Imperial Guard (1999).cat
Planetary Defence Regiment (2000).cat
Salvar Chem-Dogs (2003).cat
Steel Legion Mechanised Infantry (2000).cat
Tyranids (2001).cat

max two scything talons

---

Tau (2001).cat

Update Tau (2001).cat

---

Eldar (2000).cat

Update Eldar (2000).cat

---

Warhammer 40k 3rd Edition.gst

Added stats for pulse laser. they are in the eldar codex.

Update Warhammer 40k 3rd Edition.gst

---

Eldar (2000).cat
Warhammer 40k 3rd Edition.gst

So i fixed the witchblade. I reset the ID and changed it throughout. Ive tested this local via the newrecruit site and it works.
Also added a Melee to the profile.

Witch Blade fixes that actually fix.

---

Chaos Space Marines (2002).cat

khorne and nurgle sacred numbers were mixed up.

Update Chaos Space Marines (2002).cat

---

Imperial Guard (1999).cat

fixing commlink for the last time i hope but then again im a dumdum

Update Imperial Guard (1999).cat

---

Warhammer 40k 3rd Edition.gst

i tested this and it seems to fix the missing chainfist infolink

Chainfist infolink set hidden to false

---

Warhammer 40k 3rd Edition.gst

Added Melee - and the choppa special rule

added some missing weapon info
